### ISSUE TITLE
Editor dose not hide URL

### ISSUE THREAD

**Issue by sp3json** [lidel/yt-looper#83] opened 2015-04-14 09:28 UTC
In enabled editor "show URL button" does not hide link after clicking again

**Comment by lidel** [comment] 2015-04-14 09:32
Are you using Firefox too?

I tried to edit one of entries in sample playlist and indeed it gets stuck under Firefox: 
field with URL does not hide after clicking away nor kitting <kbd>Enter</kbd> or <kbd>Esc</kbd>:

> ![2015-04-14 11_30_32-analog sheep - i miss my amiga 500 music video](https://cloud.githubusercontent.com/assets/157609/7134089/e84245fa-e299-11e4-8f00-90f283eb0800.png)

It may be related to z-index, will investigate later.

**Comment by lidel** [comment] 2015-04-14 09:35
Duplicate of #84

**Closed by lidel** 2015-04-14 09:35 UTC
Labels: duplicate
